export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS'
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS'
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS'
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS'

export const LOADING_BEGIN = 'LOADING_BEGIN'
export const LOADING_END_SUCCESS = 'LOADING_END_SUCCESS'
export const LOADING_END_ERROR = 'LOADING_END_ERROR'